[tool.poetry]
name = "gungi"
version = "0.1.0"
description = ""
authors = ["LoveSnowEx <lsktw22@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gdtoolkit = "^4.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
